apiVersion: apps/v1
kind: Deployment
metadata:
  name: quad-ui-deployment
  labels:
    app: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: quad-client
        image: jordangrindrod/quad-client 
