---
version: '3.7'
services:
    nginx:


    server:


    client:
      environment:
      - REACT_APP_SERVICE_HOST=${REACT_APP_SERVICE_HOST}
    

    mongo:
    

    mongo-seed:
      image: fvilers/mongo-seed:1.0.0
      environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      volumes:
      - ./data:/data
      command:
      - "mongoimport --host mongo --port 27017 --db test --mode upsert --type json --file /data/account.json --jsonArray"

...

